export default[
    {
        id:1,
        title:'Volkswagen Vitrus',
        info:'The 2023 Volkswagen Virtus is a well-rounded car. Agreed, it needs to up the quality, plus fit and finish in a few areas. However, on other counts, there’s very little to complain about. It not only drives and rides well, but it’s also well-specced.',
        img:'https://assets.volkswagen.com/is/image/volkswagenag/new-virtus-01?Zml0PWNyb3AsMSZmbXQ9d2VicC1hbHBoYSZxbHQ9Nzkmd2lkPTY4MCZiZmM9b2ZmJjMzY2E=',
        year:2023,
        price:'₹ 11 47 900*'
    },
    {
        id:2,
        title:'Volkswagen Taigun',
        info:'The Volkswagen Taigun is a subcompact crossover SUV (B-segment) manufactured by the German automaker Volkswagen since 2021. Manufactured in India and destined for the Indian and Mexican markets, the Taigun is based on the Volkswagen T-Cross. The "Taigun" nameplate can be traced to 2012 when Volkswagen unveiled an unrelated smaller crossover SUV concept car with the same name. It was based on the Up city car and was planned to be mass-produced in 2016 for Europe, Brazil and India. However, the Up-based Taigun project was ultimately cancelled.',
        img:'https://assets.volkswagen.com/is/image/volkswagenag/taigun-01?Zml0PWNyb3AsMSZmbXQ9d2VicC1hbHBoYSZxbHQ9Nzkmd2lkPTY4MCZiZmM9b2ZmJjMzY2E=',
        year:2021,
        price:'From ₹11,61,900.00 ',
    },
    {
        id:3,
        title:'Mercedes Benz A-Class',
        info:'The A-Class is Mercedes entry-level subcompact car. The fourth-generation debuted for the 2018 model year. Other markets get a hatchback, but Mercedes only sells the A-Class as a sedan in the United States. It is offered in both FWD and 4Matic AWD versions with a 2.0-liter four-cylinder producing 188 hp and 221 lb-ft of torque.',
        
        img:'https://hips.hearstapps.com/amv-prod-gp.s3.amazonaws.com/gearpatrol/wp-content/uploads/2019/01/Mercedes-Benz-Explained-gear-patrol-A-Class.jpg?resize=768:*',
        year:2018,
        price:' Base MSRP $33,950',
        body:'Sedan',
        models:'A 220 4MATIC, A 220',
        engines:'2.0-liter turbocharged inline-four',
    },
    {
        id:4,
        title:'Mercedes C-Class',
        info:'The C-Class is Mercedes`s compact car. It`s available as a four-door sedan, a two-door coupe or a two-door convertible. The W206 generation is all-new for the 2022 model year. The C 43 is phasing out the V6 engine for 2.0-liter power in 2023. So is the monstrous 671 horsepower C 63 S E Performance hybrid coming for the 2024 model year.',

        img:'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/mercedes-benz-c-class-7-jpg-1652284691.jpg?crop=1.00xw:0.891xh;0,0.0862xh&resize=768:*',
        year:2022,
        price:'Base MSRP $43,550 ',
        body:'Sedan, Couple, Cabriolet',
        models:'C 300, C 300 4MATIC, AMG C 43, AMG C 63 S E Performance',
        engines:'3.0-liter turbocharged V6, 2.0-liter turbocharged inline-four, 2.0-liter turbocharged inline-four hybrid',
    },
    {
        id:5,
        title:'CLA-Class',
        info:'The second-generation CLA is Mercedes’s four-door, entry-level compact "coupe." Mercedes describes it as having “show car shape with seductive details.” The second generation debuted for 2019 and, with the A-class entering the lineup, moved a bit up market. All three versions use the base 2.0-liter twin-turbocharged inline-four. Two AMGs are on tap now: a CLA 35 making 302 hp and a CLA45 making 382 hp. All AMG CLAs are all-wheel-drive, but the 45 can be equipped with "drift mode" that turns off the front axle’s power.',
        img:'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/mercedesbenz-cla45-39-source-1600186083.jpg?crop=0.699xw:0.699xh;0.121xw,0.148xh&resize=768:*',
        year:2019,
        price:'Base MSRP $39,350',
        body:'Four-door coupe',
        models:'CLA 250, CLA 250 4MATIC, AMG CLA 35 4MATIC, AMG CLA 45 4MATIC        ',
        engines:'2.0-liter turbocharged inline-four ',
    },
    {
        id:6,
        title:'S-Class        ',
        info:'The S-Class is Mercedes’s flagship full-size sedan. It’s all-new for the 2021 model year and, as usual, it’s a technological tour de force. Coupe and cabriolet versions depart the lineup after 2021. Expect AMG versions and plug-in hybrids in the near future. For now, there are three options, each with 4MATIC AWD. There’s a six-cylinder S 500 with 429 hp, an eight-cylinder with 496 hp, and a luxurious Mercedes-Maybach version of that eight-cylinder that starts at $184,100.',
        img:'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/20c0358-059-source-1600186497.jpg?crop=0.720xw:0.716xh;0.221xw,0.240xh&resize=768:*',
        year:2021,
        price:'$111,100',
        body:'Sedan',
        models:'S 500 4MATIC, S 580 4MATIC, Mercedes-Maybach S580 4MATIC        ',
        engines:'3.0-liter turbocharged inline-six w/EQ Boost, 4.0-liter turbocharged V8 w/EQ Boost        ',
    },
    {
        id:7,
        title:'AMG GT        ',
        info:'The AMG GT cars are Mercedes’s high-performance sports cars. The AMG GT comes as either a two-door or a four-door vehicle. The two-door model can be a coupe or a roadster. Four-door V8 versions are no longer available on the Mercedes website. A new generation is due to arrive in 2023.',
        img:'https://hips.hearstapps.com/amv-prod-gp.s3.amazonaws.com/gearpatrol/wp-content/uploads/2019/01/Mercedes-Benz-Explained-gear-patrol-AMG-GT-Class.jpg?resize=768:*',
        year:2021,
        price:' $92,500',
        body:'Four-door coupe, Coupe, Roadster ',
        models:'AMG GT 43 4MATIC, AMG GT 53 4MATIC, GT (Coupe, Roadster), GT C (Coupe, Roadster), GT Black Series (Coupe)',
        engines:'3.0-liter turbocharged inline-six w/EQ Boost, 4.0-liter turbocharged V8        ',
    },
    {
        id: 8,
        title:'SL Roadster        ',
        info:'Mercedes brought the SL Roadster back for the 2022 model year. Unlike the outgoing vehicle, it’s a more hard-edged sports car built to take on the likes of the Porsche 911. It’s AMG developed. It’s only currently offered with an AMG V8. And for the first time in the model line’s history, it’s only offered with AWD. The upcoming AMG GT will likely be a hard roof version of the SL.',
        img:'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/mercedes-amg-sl-class-2022-11-1641326922.jpeg?crop=1.00xw:0.891xh;0,0.109xh&resize=768:*',
        year:2021,
        price:'$137,400',
        body:'Roadster',
        models:'AMG SL 55 Roadster, AMG SL 63 Roadster        ',
        engines:'4.0-liter turbocharged V8',
    },
    {
        id:9,
        title:'G-Class',
        info:'The G-Wagen is Mercedes’s boxy, off-road-capable body-on-frame midsize SUV. The current second generation debuted for 2018. There are two versions, the 416 hp G 550 and the 577 hp AMG G 63. The latter may be the most capable all-around vehicle on the market. It’s great at everything except consuming fuel efficiently. Mercedes is planning to branch the G-Class into its own "G" sub-brand and will produce an EQG electric version.',
        img:'https://hips.hearstapps.com/amv-prod-gp.s3.amazonaws.com/gearpatrol/wp-content/uploads/2019/05/2019-Mercedes-AMG-G63-Review-gear-patrol-slide-6.jpg?crop=1xw:0.9948717948717948xh;center,top&resize=768:*',
        year:2018,
        price:' $139,900',
        body:'SUV',
        models:'G 550,  AMG G 63',
        engines:'4.0-liter turbocharged V8',
    },
    {
        id:10,
        title:'New Suzuki Jimny',
        info:'The Jimny, which was released in 1970 and is the only full-fledged cross-country 4WD mini vehicle, takes advantage of its compact body to demonstrate overwhelming ability to travel on rough roads, making it unique in Japan and other countries around the world. We have received high acclaim and are needed as a company. With this full model change, the first in 20 years, we have pursued a design that is reasonable and streamlined and befits a professional tool for all users who need the Jimny. We have further refined the Jimny`s outstanding vehicle feel, contributing to its ability to drive on rough roads, and created a highly practical car that is fully functional, from loadability and maneuverability to interior and exterior coloring.',
        img:'https://hips.hearstapps.com/amv-prod-gp.s3.amazonaws.com/gearpatrol/wp-content/uploads/2018/10/Suzuki-Jimny-Design-Award-gear-patrol-slide-2.jpg?resize=980:*&keepGifs=1',
        year:2023,
        price:'$45,000',
        body:'SUV',
        models:'Off-Roader',
        engines:'1462cc',
    },


]